+fparsec +fraylib +fsandbox +fcolors +ft8 +fterminal-guillotine +fdocker(add fdocker ls command)

diff --git a/fdocker b/fdocker
--- a/fdocker
+++ b/fdocker
@@ -1,16 +1,16 @@
 #!/bin/bash
 
 if [ "$#" -ne 1 ]; then
-    echo "Usage: $0 <docker/compose> "
+    echo "Usage: $0 <docker/compose/ls> "
     exit 1
 fi
 
 PROMPT="$1"
 
-if [ "$PROMPT" != "docker" ] && [ "$PROMPT" != compose ]; then
-    echo "Error : $PROMPT. <docker/compose>"
-    exit 2
-fi
+# if [ "$PROMPT" != "docker" ] && [ "$PROMPT" != "compose" ] && && [ "$PROMPT" != "ls" ]; then
+    # echo "Error : $PROMPT. <docker/compose>"
+    # exit 2
+# fi
 
 if [ "$PROMPT" = "docker" ]; then
     sudo apt update
@@ -32,6 +32,23 @@ if [ "$PROMPT" = "compose" ]; then
     sudo chmod +x /usr/local/bin/docker-compose
     sudo apt update
     docker-compose --version
+    exit 0
+fi
+
+if [ "$PROMPT" = "ls" ]; then
+    printf "\033[1;32m"
+    docker ps -a
+
+    printf "\033[1;33m"
+    docker image ls
+
+    printf "\033[1;34m"
+    docker volume ls
+
+    printf "\033[1;35m"
+    docker network ls
+
+    printf "\033[0m\n"
     exit 0
 fi
 
